-- School year support
-- Stores all known school years and marks exactly one as current.

create table if not exists public.school_years (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  label text not null unique,
  is_current boolean not null default false
);

alter table public.school_years enable row level security;

-- Ensure at most one current year.
create unique index if not exists school_years_single_current
on public.school_years (is_current)
where is_current;

-- Grants (match the existing pattern)
grant delete on table public.school_years to anon;
grant insert on table public.school_years to anon;
grant references on table public.school_years to anon;
grant select on table public.school_years to anon;
grant trigger on table public.school_years to anon;
grant truncate on table public.school_years to anon;
grant update on table public.school_years to anon;

grant delete on table public.school_years to authenticated;
grant insert on table public.school_years to authenticated;
grant references on table public.school_years to authenticated;
grant select on table public.school_years to authenticated;
grant trigger on table public.school_years to authenticated;
grant truncate on table public.school_years to authenticated;
grant update on table public.school_years to authenticated;

grant delete on table public.school_years to service_role;
grant insert on table public.school_years to service_role;
grant references on table public.school_years to service_role;
grant select on table public.school_years to service_role;
grant trigger on table public.school_years to service_role;
grant truncate on table public.school_years to service_role;
grant update on table public.school_years to service_role;

-- Helper predicate for admin-only mutation.
create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.users u
    where u.auth_id = auth.uid()
      and coalesce(u.admin, false) = true
      and coalesce(u.active, true) = true
  );
$$;

-- Read access for everyone.
create policy "Enable read access for all users"
on public.school_years
as permissive
for select
to public
using (true);

-- Only admins can mutate school_years.
create policy "Enable insert for admins"
on public.school_years
as permissive
for insert
to authenticated
with check (public.is_admin_user());

create policy "Enable update for admins"
on public.school_years
as permissive
for update
to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "Enable delete for admins"
on public.school_years
as permissive
for delete
to authenticated
using (public.is_admin_user());

-- Return the current school year label (or null if none)
create or replace function public.get_current_school_year()
returns text
language sql
stable
as $$
  select sy.label
  from public.school_years sy
  where sy.is_current = true
  limit 1;
$$;

grant execute on function public.get_current_school_year() to anon;
grant execute on function public.get_current_school_year() to authenticated;

-- Advance to next year based on the current label (expects format YYYY-YY)
create or replace function public.advance_school_year()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_label text;
  start_year int;
  next_start int;
  next_end_two int;
  next_label text;
begin
  if not public.is_admin_user() then
    raise exception 'not authorized';
  end if;

  select label into current_label
  from public.school_years
  where is_current = true
  limit 1;

  if current_label is null then
    raise exception 'no current school year set';
  end if;

  start_year := split_part(current_label, '-', 1)::int;
  next_start := start_year + 1;
  next_end_two := (next_start + 1) % 100;
  next_label := next_start::text || '-' || lpad(next_end_two::text, 2, '0');

  update public.school_years
  set is_current = false
  where is_current = true;

  insert into public.school_years(label, is_current)
  values (next_label, true)
  on conflict (label)
  do update set is_current = true;

  return next_label;
end;
$$;

grant execute on function public.advance_school_year() to authenticated;

-- Seed a default year only if the table is empty.
do $$
begin
  if not exists (select 1 from public.school_years) then
    insert into public.school_years(label, is_current)
    values ('2024-25', true);
  end if;
end $$;
